[project]
name = "cicada-gsoc-evaluation-task"
version = "0.1.0"
description = "Solution to Cicada's GSOC evaluation task by Mann Acharya (@mach-12)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
